# Generated by Django 6.0 on 2025-12-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='registration_paper',
            field=models.FileField(blank=True, null=True, upload_to='registration_papers/'),
        ),
    ]
