# Generated by Django 6.0 on 2025-12-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_registration_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='approval_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
