# Generated by Django 6.0 on 2025-12-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_dashcam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='has_seatcovers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='has_tinting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='has_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
