# Generated by Django 6.0 on 2025-12-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_order_has_dashcam_order_has_seatcovers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
    ]
